app/catalog/forms.py
from flask.ext.wtf import Form
from flask.ext.mongoengine.wtf import model_form

from flask.ext.babel import gettext as _

from wtforms import StringField,SelectMultipleField,BooleanField,SubmitField,SelectField,FloatField,DecimalField,IntegerField
from wtforms.validators import DataRequired,Email,Length,Regexp,EqualTo
from wtforms import ValidationError

from .model import Category,ProductGallery,Product
from app.dashboard.model import Website

def get_category_tree():

    """
    SELECT CONCAT( REPEAT(' ', COUNT(parent.name) - 1), node.name) AS name
    FROM nested_category AS node,
            nested_category AS parent
    WHERE node.lft BETWEEN parent.lft AND parent.rgt
    GROUP BY node.name
    ORDER BY node.lft;
    """

    result = [(None,_("-- Please Select --"))]
    categories = Category.objects().order_by("lft")
    for category in categories:
        result.append((str(category.id),category.name))
    return result



class ProductForm(Form):
    category = SelectMultipleField(_("Category"), choices=get_category_tree())
    name = StringField(_('Name'), validators=[DataRequired()])
    chinese = StringField(_('Chinese name'), validators=[DataRequired()])
    sku = StringField(_('SKU'), validators=[DataRequired()])
    weight = FloatField(_('Weight'), validators=[DataRequired()])
    price = DecimalField(_('Price'), validators=[DataRequired()])
    cost = DecimalField(_('Cost'), validators=[DataRequired()])
    status = BooleanField(_("Status"), default=True, validators=[DataRequired()])
    qty = IntegerField(_("Qty"))
    is_in_stock = BooleanField(_("Stock Availability"), default=False, validators=[DataRequired()])
    submit = SubmitField(_('Submit'))



class CategoryForm(Form):
    parent = SelectField(_("Parent"),choices=get_category_tree())
    name = StringField(_('Name'),validators=[DataRequired()])
    submit = SubmitField(_('Submit'))


    def validate_parent(form,field):
        if field.data:
            category = Category.objects.get(pk=field.data)
            if category:
                field.data = category
            else:
                raise ValidationError('Parent must exists')

        else:
            field.data = None

app/catalog/views.py
#/usr/bin/env python
#-*- coding:utf8 -*-
import os
from flask import request,redirect,render_template,url_for,flash,Blueprint
from flask.ext.login import login_required
from flask.ext.babel import gettext as _
from app import settings
from app.core import app
from .model import Category,Product,ProductGallery
from .forms import CategoryForm, ProductForm

#from app.dashboard.model import Website

catalog = Blueprint('catalog', __name__,url_prefix='/catalog',template_folder=os.path.join(settings.TEMPLATE_FOLDER,'catalog'))


@catalog.route('/category')
@catalog.route('/category/<int:page>')
@login_required
def category(page=1):
    pagination = Category.objects.order_by("-id").paginate(page = page, per_page=10)
    return render_template('category/list.html', categories=pagination.items, pagination=pagination)


@catalog.route('/category/import/<website>',endpoint='import_category')
@login_required
def import_category(website):
    pass
    #website = Website.objects.get_or_404(id=website)



@catalog.route('/category/add/',endpoint='add_category',methods=['GET','POST'])
@catalog.route('/category/edit/<id>',endpoint='edit_category',methods=['GET','POST'])
@login_required
def add_category(id = None):
    form = CategoryForm()
    if form.validate_on_submit():
        category = Category(
                    parent=form.parent.data,
                    name = form.name.data,
                    )
        category.save()
        flash(_('Category add successful'))
        return redirect(url_for('catalog.category'))


    return render_template('category/add.html',form=form, breadcrumb=['Home','Category'])



@catalog.route('/product')
@catalog.route('/product/<int:page>')
@login_required
def product(page=1):
    pagination = Product.objects.order_by("-id").paginate(page = page, per_page=10)
    return render_template('product/list.html', products=pagination.items, pagination=pagination)



@catalog.route('/product/add', endpoint='add_product',methods=['GET','POST'])
def add_product():
    form = ProductForm()
    if form.validate_on_submit():
        pass

        flash(_('Product add successful'))
        return redirect(url_for('catalog.category'))

    return  render_template('product/add.html',form=form)





app.register_blueprint(catalog)

templates/catalog/category/add.html
{% extends "admin.html" %}
{% block main %}
     {{super()}}
        <div class="row">

            <div class="col-md-8">
                <div class="block">
                    <div class="content controls">
                        <div class="form-row">
                            <div class="col-md-2">{{ _('Name')}}:</div>
                            <div class="col-md-10"><input type="text" class="form-control"></div>
                        </div>
                         <div class="form-row">
                            <div class="col-md-2">{{_('Parent')}}:</div>
                            <div class="col-md-10">

                                <select class="select2" multiple="multiple" style="width: 100%;" tabindex="-1">
                                        <option value="AZ">Arizona</option>
                                        <option value="CO">Colorado</option>
                                        <option value="ID">Idaho</option>
                                        <option value="MT" selected="selected">Montana</option>
                                        <option value="NE">Nebraska</option>
                                        <option value="NM">New Mexico</option>
                                        <option value="ND">North Dakota</option>
                                        <option value="UT">Utah</option>
                                        <option value="WY">Wyoming</option>
                                </select>

                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-md-2">Date and time:</div>
                            <div class="col-md-10">
                                <div class="input-group">
                                    <div class="input-group-addon"><span class="icon-globe"></span></div>
                                    <input type="text" class="datetimepicker form-control"/>

                                </div>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="col-md-2">{{_('Description')}}</div>
                            <div class="col-md-10">
                                <div class="input-group">
                                    <div class="content np">
                                    <textarea class="cle"></textarea>
                                        </div>
                                </div>
                            </div>
                        </div>
                         <div class="form-row">
                             <div class="col-md-12">
                               <div class="input-group pull-right">
                                  <button type="button" class="btn btn-default">{{_('Submit')}}</button>
                                </div>

                                 </div>
                         </div>
                    </div>


                </div><!-- block -->
            </div><!-- col-md-6-->
            <div class="col-md-4"></div><!-- col-md-6-->
        </div><!-- row -->
{% endblock %}

{% block custom_scripts %}
    <script type='text/javascript' src="{{url_for('static', filename='js/plugins/select2/select2.min.js')}}"></script>
    <script type='text/javascript' src="{{url_for('static', filename='js/plugins/tagsinput/jquery.tagsinput.min.js')}}"></script>
    <script type='text/javascript' src="{{url_for('static', filename='js/plugins/jquery/jquery-ui-timepicker-addon.js')}}"></script>
    <script type='text/javascript' src="{{url_for('static', filename='js/plugins/ibutton/jquery.ibutton.js')}}"></script>
    <script type='text/javascript' src="{{url_for('static', filename='js/plugins/cleditor/jquery.cleditor.min.js')}}"></script>

 {% endblock %}

templates/catalog/category/list.html
{% extends "admin.html" %}
{% block main %}
        {{super()}}
        <div class="row">
            <div class="col-md-12">

                <div class="block">
                    <div class="header">
                        <h2>{{_('Categories')}}</h2>
                    </div>
                    <div class="content">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                                <tr>
                                    <th style="width: 18px;"><input type="checkbox" class="checkall"/></th>
                                    <th>{{_('Name')}}</th>
                                    <th>{{_('Parent')}}</th>
                                    <th>{{_('Created On')}}</th>
                                    <th>{{_('Status')}}</th>
                                    <th>{{_('Action')}}</th>
                                </tr>
                            </thead>
                            <tbody>
                             {% for category in categories %}
                                <tr>
                                    <td><input type="checkbox" name="checkbox"/></td>
                                    <td>{{category.name}}</td>
                                    <td>{{category.parent.name}}</td>
                                    <td>{{category.created_at}}</td>
                                    <td>{{category.status}}</td>
                                    <td><a href="{{url_for('catalog.edit_category',id=category.id)}}">{{_("View")}}</a> &nbsp; <a href="{{url_for('catalog.add_category',id=category.id)}}">{{_("Delete")}}</a></td>
                                </tr>
                             {% endfor %}
                            </tbody>
                            <tfoot>
                            <tr>
                                <td colspan="6">
                                    <div class="dataTables_paginate paging_simple_numbers" id="dataTables-customer_paginate">
                                        {{ macros.pagination(pagination, 'catalog.category') }}
                                    </div>
                                </td>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>

            </div>
        </div>
{% endblock %}