app/dashboard/forms.py
from flask.ext.wtf import Form
from flask.ext.babel import gettext as _
from wtforms import StringField,PasswordField,BooleanField,SubmitField,SelectField
from wtforms.validators import DataRequired,Email,Length,Regexp,EqualTo
from wtforms import ValidationError
from .model import Website
from app import get_api_type_select



class WebsiteForm(Form):

    name = StringField(_('Website name'),validators=[DataRequired()])
    code = StringField(_('Code name'),validators=[DataRequired()])
    type = SelectField(_('Type'),choices=get_api_type_select())
    link = StringField(_('API link'),validators=[DataRequired()])
    key = StringField(_('API key'),validators=[DataRequired()])
    secret = StringField(_('API secret'),validators=[DataRequired()])
    submit = SubmitField(_('Submit'))


    def validate_code(self, field):
        if Website.objects.filter(code=field.data).first():
            raise ValidationError('Code already exists.')

app/catalog/views.py
#/usr/bin/env python
#-*- coding:utf8 -*-
import os
from flask import request,redirect,render_template,url_for,flash,Blueprint
from flask.ext.login import login_required
from flask.ext.babel import gettext as _
from app import settings
from app.core import app
from .model import Category,Product,ProductGallery
from .forms import CategoryForm, ProductForm

#from app.dashboard.model import Website

catalog = Blueprint('catalog', __name__,url_prefix='/catalog',template_folder=os.path.join(settings.TEMPLATE_FOLDER,'catalog'))


@catalog.route('/category')
@catalog.route('/category/<int:page>')
@login_required
def category(page=1):
    pagination = Category.objects.order_by("-id").paginate(page = page, per_page=10)
    return render_template('category/list.html', categories=pagination.items, pagination=pagination)


@catalog.route('/category/import/<website>',endpoint='import_category')
@login_required
def import_category(website):
    pass
    #website = Website.objects.get_or_404(id=website)



@catalog.route('/category/add/',endpoint='add_category',methods=['GET','POST'])
@catalog.route('/category/edit/<id>',endpoint='edit_category',methods=['GET','POST'])
@login_required
def add_category(id = None):
    form = CategoryForm()
    if form.validate_on_submit():
        category = Category(
                    parent=form.parent.data,
                    name = form.name.data,
                    )
        category.save()
        flash(_('Category add successful'))
        return redirect(url_for('catalog.category'))


    return render_template('category/add.html',form=form, breadcrumb=['Home','Category'])



@catalog.route('/product')
@catalog.route('/product/<int:page>')
@login_required
def product(page=1):
    pagination = Product.objects.order_by("-id").paginate(page = page, per_page=10)
    return render_template('product/list.html', products=pagination.items, pagination=pagination)



@catalog.route('/product/add', endpoint='add_product',methods=['GET','POST'])
def add_product():
    form = ProductForm()
    if form.validate_on_submit():
        pass

        flash(_('Product add successful'))
        return redirect(url_for('catalog.category'))

    return  render_template('product/add.html',form=form)





app.register_blueprint(catalog)

app/customers/views.py
#/usr/bin/env python
#-*- coding:utf8 -*-
import os
from flask import request,redirect,render_template,url_for,flash,Blueprint,current_app
from flask.ext.login import login_required
from flask.ext.babel import gettext as _


from app import settings
from app.core import app,db
from app.customers.model import Customer

from app.customers.forms import CustomerForm


customers = Blueprint('customers', __name__,url_prefix='/customers',template_folder=os.path.join(settings.TEMPLATE_FOLDER,'customers'))



@customers.route('/')
@customers.route('/customer/<int:page>/')
@login_required
def customer(page = 1):
    #page = (Customer.query.count() - 1) / current_app.config['LIST_PER_PAGE'] + 1
    pagination = Customer.objects.order_by("-id").paginate(page = page, per_page=10, error_out=False)
    return render_template('customers.html',customers = pagination.items,pagination=pagination)


@customers.route('/group/')
@customers.route('/group/<int:page>/')
@login_required
def group(page = 1):
    #page = (Customer.query.count() - 1) / current_app.config['LIST_PER_PAGE'] + 1
    pagination = Customer.query.order_by(Customer.id.desc()).paginate(page = page, per_page=10, error_out=False)
    return render_template('customers.html',customers = pagination.items,pagination=pagination)


@customers.route('/address/')
@customers.route('/address/<int:page>/')
@login_required
def address(page = 1):
    #page = (Customer.query.count() - 1) / current_app.config['LIST_PER_PAGE'] + 1
    pagination = Customer.query.order_by(Customer.id.desc()).paginate(page = page, per_page=10, error_out=False)
    return render_template('customers.html',customers = pagination.items,pagination=pagination)




@customers.route('/add/', endpoint='add_customer', methods = ['GET','POST'])
@login_required
def add():
    form = CustomerForm()
    if form.validate_on_submit():

        user = Customer(email=form.email.data,
                    firstname=form.firstname.data,
                    lastname=form.lastname.data,
                    website_id = form.website_id.data.id,
                    group_id = form.group_id.data
                    )

        db.session.add(user)
        db.session.commit()
        flash(_('Customer add successful'))
        return redirect(url_for('customers.index'))


    return render_template('add.html',form=form)

@customers.route('/view/<int:id>')
@login_required
def view():
    return render_template('message.html')





app.register_blueprint(customers)

app/dashboard/views.py
#/usr/bin/env python
#-*- coding:utf8 -*-
import os
from flask import request,redirect,render_template,url_for,flash,Blueprint,g
from flask.ext.login import login_required,current_user
from flask.ext.babel import gettext as _
from app import settings
from app.core import app
from .model import Website
from .forms import WebsiteForm
system = Blueprint('system', __name__, url_prefix='/system', template_folder=os.path.join(settings.TEMPLATE_FOLDER,'system'))

@system.route('/')
@login_required
def dashboard():
    flash("Login in lasdf")
    return render_template('dashboard.html',title='Dashboard')


@system.route("/website/delete/<id>", endpoint='delete_website')
@login_required
def delete_website(id):
    website = Website.objects.get_or_404(id=id)
    website.delete()
    flash(_('Website deleted successful'))
    return redirect(url_for('system.website'))

@system.route("/website", methods=['GET','POST'])
@login_required
def website():
    websites = Website.objects.all()
    form = WebsiteForm()
    if form.validate_on_submit():


        config = {
            'api':form.key.data,
            'secret': form.secret.data
        }

        website = Website(
                    code=form.code.data,
                    name = form.name.data,
                    type = form.type.data,
                    link = form.link.data,
                    config = config,
                    #key = form.key.data,
                    #secret = form.secret.data,
                    )
        website.save()
        flash(_('Website add successful'))
        return redirect(url_for('system.website'))

    return render_template('website.html',title=_('Website'), websites=websites, form=form)


@system.route('/message')
@login_required
def message():
    return render_template('message.html')


@system.route('/alerts')
@login_required
def alerts():
    return render_template('alerts.html')


@system.route('/tasks')
@login_required
def tasks():
    return render_template('tasks.html')

@system.route('/settings',methods = ['GET','POST'])
@login_required
def settings():
    return render_template('settings.html')

app.register_blueprint(system)

app/sales/views.py
#/usr/bin/env python
#-*- coding:utf8 -*-
import os
from flask import request,redirect,render_template,url_for,flash,Blueprint
from flask.ext.login import login_required
from app import settings
from app.core import app

from app.sales.model import Order,Shipment,Invoice


sales = Blueprint('sales', __name__,url_prefix='/sales',template_folder=os.path.join(settings.TEMPLATE_FOLDER,'sales'))


@sales.route('/order/')
@sales.route('/order/<int:page>/')
@login_required
def order(page = 1):
    pagination = Order.query.order_by(Order.id.desc()).paginate(page = page, per_page=10, error_out=False)
    return render_template('order/list.html',orders = pagination.items,pagination=pagination)


@sales.route('/order/view/<int:id>/')
@login_required
def order_view(id):
    order = Order.query.get_or_404(id)
    return render_template('order/view.html',order = order)


@sales.route('/shipment/')
@login_required
def shipment():
    return render_template('shipment.html')


@sales.route('/payment/')
@login_required
def payment():
    pass

@sales.route('/invoice/')
@login_required
def invoice():
    pass



app.register_blueprint(sales)

templates/_macros.html
{% macro address(address) %}
<address>
    {{address.id}}
      <strong>{{address.firstname}} {{address.lastname}}</strong>
      <br>{{address.street}}
      <br>{{address.city}}, {{address.region}} {{address.postcode}}
      <br>
      <abbr title="Phone">P:</abbr>{{address.telephone}}
</address>
{% endmacro %}


{% macro breadcrumb(breadcrumb = None) %}
    {% if breadcrumb %}
 <ol class="breadcrumb">
     {% for b in breadcrumb %}
     <li><a href="#">Home</a></li>

     {% endfor %}
     <li><a href="#">Pages</a></li>
     <li class="active">Invoice</li>
</ol>
        {% endif %}
{% endmacro %}

{% macro pagination(pagination, endpoint, fragment='') %}
    <ul class="pagination">
        <li class="paginate_button previous {% if not pagination.has_prev %}disabled{% endif %}"  tabindex="0" id="dataTables-customer_previous">
                <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{{ fragment }}{% else %}javascript:void(0){% endif %}">
                    {{_('Previous')}}
                </a>
        </li>
       {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="paginate_button active">
                <span>{{ p }}</span>
            </li>
            {% else %}
            <li class="paginate_button ">
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="javascript:void(0)">&hellip;</a></li>
        {% endif %}
    {% endfor %}
        <li class="paginate_button next {% if not pagination.has_next %}disabled{% endif %}" tabindex="0" id="dataTables-customer_next">
            <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{{ fragment }}{% else %}javascript:void(0){% endif %}">
                {{_('Next')}}
            </a>
        </li>
    </ul>
{% endmacro %}

templates/admin.html
{% extends "base.html" %}
 {% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                {% block top_nav %}
                 <nav class="navbar brb" role="navigation">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-reorder"></span>
                        </button>
                        <a class="navbar-brand" href="{{ url_for('system.dashboard') }}"><img src="{{url_for('static', filename='img/logo.png')}}"/></a>
                    </div>
                    <div class="collapse navbar-collapse navbar-ex1-collapse">
                        <ul class="nav navbar-nav">
                            <li class="active">
                                <a href="{{ url_for('system.dashboard') }}">
                                    <span class="icon-home"></span>{{ _('Dashboard')}}</a>
                            </li>
                            <li class="dropdown">
                                <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><span class="icon-globe"></span>{{_('Sales')}}</a>
                                <ul class="dropdown-menu">
                                    <li><a href="{{ url_for('sales.order') }}">{{ _('Orders') }}</a></li>
                                   <li><a href="{{ url_for('sales.shipment') }}">{{ _('Invoices') }}</a></li>
                                    <li><a href="{{ url_for('sales.shipment') }}">{{ _('Shipments') }}</a></li>
                                    <li><a href="{{ url_for('sales.shipment') }}">{{ _('Credit Memos') }}</a></li>
                                    <li><a href="{{ url_for('sales.shipment') }}">{{ _('Returns') }}</a></li>
                                    <li><a href="{{ url_for('sales.shipment') }}">{{ _('Transactions') }}</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><span class="icon-cogs"></span>{{ _('Catalog') }}</a>
                                <ul class="dropdown-menu">
                                      <li><a href="{{ url_for('catalog.category') }}">{{ _('Category') }}</a></li>
                                      <li><a href="{{ url_for('catalog.product') }}">{{ _('Product') }}</a></li>
                                </ul>
                            </li>

                            <li class="dropdown">
                                <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><span class="icon-file-alt"></span>{{ _('Customer') }}</a>
                                <ul class="dropdown-menu">
                                    <li><a href="{{ url_for('customers.customer') }}">{{ _('Customer') }}</a></li>
                                    <li><a href="{{ url_for('customers.group') }}">{{ _('Customer Group') }}</a></li>
                                    <li><a href="{{ url_for('customers.address') }}">{{ _('Address') }}</a></li>
                                    <li><a href="{{ url_for('customers.address') }}">{{ _('Message') }}</a></li>
                                    <!--
                                    <li>
                                        <a href="#">Error pages<i class="icon-angle-right pull-right"></i></a>
                                        <ul class="dropdown-submenu">
                                            <li><a href="sample_error_403.html">403 Forbidden</a></li>
                                            <li><a href="sample_error_404.html">404 Not Found</a></li>
                                            <li><a href="sample_error_500.html">500 Internal Server Error</a></li>
                                            <li><a href="sample_error_503.html">503 Service Unavailable</a></li>
                                            <li><a href="sample_error_504.html">504 Gateway Timeout</a></li>
                                        </ul>
                                    </li>
                                    -->
                                </ul>
                            </li>


                            <li class="dropdown">
                                <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><span class="icon-cogs"></span>{{ _('System') }}</a>
                                <ul class="dropdown-menu">
                                     <li><a href="{{ url_for('system.website') }}">{{ _('Website') }}</a></li>
                                     <li><a href="{{ url_for('customers.group') }}">{{ _('Languages') }}</a></li>
                                     <li><a href="{{ url_for('customers.address') }}">{{ _('Address') }}</a></li>
                                </ul>
                            </li>
                        </ul>
                        <form class="navbar-form navbar-right" role="search">
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="search..."/>
                            </div>
                        </form>
                    </div>
                </nav>
                {% endblock %}
            </div>
        </div> <!-- nav row end -->

        {{ macros.breadcrumb(breadcrumb) }}

        {% block main %}
        {% endblock %}
        <div class="row">
            <div class="page-footer">
                <div class="page-footer-wrap">
                    <div class="side pull-left">
                        {{ _('Copyirght &COPY; Flasky 2014. All rights reserved.')}}
                    </div>
                </div>
            </div>
        </div> <!-- footer row end -->
</div><!-- container end-->

        {% endblock %}

templates/base.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "bootstrap/fixes.html" as fixes %}
{% import "_macros.html" as macros %}
{% block head %}
  {{super()}}
  {{fixes.ie8()}}
{% endblock %}
{% block styles %}
    {{super()}}
 <link href="{{url_for('static', filename='css/stylesheets.css')}}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block scripts %}
    {{super()}}

    <script type='text/javascript' src="{{url_for('static', filename='js/plugins/jquery/jquery-ui.min.js')}}"></script>
    <script type='text/javascript' src="{{url_for('static', filename='js/plugins/jquery/jquery-migrate.min.js')}}"></script>
    <script type='text/javascript' src="{{url_for('static', filename='js/plugins/jquery/globalize.js')}}"></script>
    <script type='text/javascript' src="{{url_for('static', filename='js/plugins/uniform/jquery.uniform.min.js')}}"></script>
    {% block custom_scripts %}
    {% endblock %}
    <script type='text/javascript' src="{{url_for('static', filename='js/plugins.js')}}"></script>
    <script type='text/javascript' src="{{url_for('static', filename='js/actions.js')}}"></script>
    <script type='text/javascript' src="{{url_for('static', filename='js/settings.js')}}"></script>
{% endblock %}

templates/dashboard.html
{% extends "admin.html" %}
        {% block main %}
       {{ super() }}
        {% endblock%}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>        
    <title>Taurus</title>
    
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    
    <link rel="icon" type="image/ico" href="favicon.ico"/>
    

    
    <script type='text/javascript' src='js/plugins/jquery/jquery.min.js'></script>
    <script type='text/javascript' src='js/plugins/jquery/jquery-ui.min.js'></script>   
    <script type='text/javascript' src='js/plugins/jquery/jquery-migrate.min.js'></script>
    <script type='text/javascript' src='js/plugins/jquery/globalize.js'></script>    
    <script type='text/javascript' src='js/plugins/bootstrap/bootstrap.min.js'></script>
    
    <script type='text/javascript' src='js/plugins/uniform/jquery.uniform.min.js'></script>
    
    <script type='text/javascript' src='js/plugins.js'></script>    
    <script type='text/javascript' src='js/actions.js'></script>    
    <script type='text/javascript' src='js/settings.js'></script>
</head>
<body class="bg-img-num1"> 
    
    <div class="container">        

        <div class="login-block">
            <div class="block block-transparent">
                <div class="head">
                    <div class="user">
                        <div class="info user-change">                                                                                
                            <img src="img/example/user/dmitry_b.jpg" class="img-circle img-thumbnail"/>
                            <div class="user-change-button">
                                <span class="icon-off"></span>
                            </div>
                        </div>                            
                    </div>
                </div>
                <div class="content controls npt">
                    <div class="form-row user-change-row">
                        <div class="col-md-12">
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <span class="icon-user"></span>
                                </div>
                                <input type="text" class="form-control" placeholder="Login"/>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-12">
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <span class="icon-key"></span>
                                </div>
                                <input type="password" class="form-control" placeholder="Password"/>
                            </div>
                        </div>
                    </div>                        
                    <div class="form-row">
                        <div class="col-md-6">
                            <a href="#" class="btn btn-default btn-block btn-clean">Register</a>                                
                        </div>
                        <div class="col-md-6">
                            <a href="#" class="btn btn-default btn-block btn-clean">Log In</a>
                        </div>
                    </div>
                    <div class="form-row">                            
                        <div class="col-md-12">
                            <a href="#" class="btn btn-link btn-block">Forgot your password?</a>
                        </div>
                    </div>                         
                    <div class="form-row">
                        <div class="col-md-12 tac"><strong>OR USE</strong></div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-12">
                            <a href="#" class="btn btn-info btn-block"><span class="icon-facebook"></span> &nbsp; Facebook</a>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-12">
                            <a href="#" class="btn btn-primary btn-block"><span class="icon-twitter"></span> &nbsp; Tweeter</a>
                        </div>
                    </div>                    
                </div>
            </div>
        </div>

    </div>

</body>
</html>